version: '3.7'

services:
  near-data-analyze:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: api-and-grabber
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run start